{
  "Graph": {
    "Kind": "Action",
    "Variables": [],
    "Nodes": [
      {
        "Id": 0,
        "Type": "input",
        "Properties": {
          "parameters": [
            {
              "Name": "value",
              "Type": "System.Private.CoreLib/System.String",
              "IsRequired": true
            }
          ]
        },
        "UserData": {
          "Position": "-240,-16"
        }
      },
      {
        "Id": 1,
        "Type": "log.info",
        "Inputs": {
          "format": "Hello, {0}!"
        },
        "UserData": {
          "Position": "80,-32"
        }
      }
    ],
    "Links": [
      [
        0,
        "_signal",
        1,
        "_signal"
      ],
      [
        0,
        "value",
        1,
        "args",
        0
      ]
    ],
    "UserData": {
      "Title": "Greeter",
      "Description": "Says hello to the input.",
      "id": "1edf82bc-0c61-4efd-9955-7024a589b7e2",
      "Icon": "emoji_people",
      "Category": "Custom"
    }
  },
  "__references": []
}