namespace Sandbox.Clutter;

/// <summary>
/// Immutable settings for clutter generation.
/// Used to detect changes and configure the grid system.
/// </summary>
public readonly record struct ClutterSettings
{
	public int RandomSeed { get; init; }
	public ClutterDefinition Clutter { get; init; }
	public Scatterer Scatterer { get; init; }

	public ClutterSettings( int randomSeed, ClutterDefinition definition )
	{
		RandomSeed = randomSeed;
		Clutter = definition;
		Scatterer = definition?.Scatterer;
	}

	/// <summary>
	/// Validates that settings are ready for clutter generation.
	/// </summary>
	public bool IsValid => Clutter != null && Scatterer != null;

	/// <summary>
	/// Hash automatically generated by record struct.
	/// Includes all properties for change detection.
	/// </summary>
	public override int GetHashCode()
	{
		return HashCode.Combine(
			Clutter.TileSize,
			Clutter.TileRadius,
			RandomSeed,
			Clutter?.GetHashCode() ?? 0,
			Scatterer?.GetHashCode() ?? 0
		);
	}
}
