namespace Sandbox;

/// <summary>
/// Immutable settings for clutter generation.
/// Used to detect changes and configure the grid system.
/// </summary>
public readonly record struct ClutterSettings
{
	public float TileSize { get; init; }
	public int TileRadius { get; init; }
	public int RandomSeed { get; init; }
	public ClutterIsotope Isotope { get; init; }
	public Scatterer Scatterer { get; init; }

	public ClutterSettings( float tileSize, int tileRadius, int randomSeed, ClutterIsotope isotope )
	{
		TileSize = tileSize;
		TileRadius = tileRadius;
		RandomSeed = randomSeed;
		Isotope = isotope;
		Scatterer = isotope?.Scatterer;
	}

	/// <summary>
	/// Validates that settings are ready for clutter generation.
	/// </summary>
	public bool IsValid => Isotope != null && Scatterer != null;

	/// <summary>
	/// Hash automatically generated by record struct.
	/// Includes all properties for change detection.
	/// </summary>
	public override int GetHashCode()
	{
		return HashCode.Combine(
			TileSize,
			TileRadius,
			RandomSeed,
			Isotope?.GetHashCode() ?? 0,
			Scatterer?.GetHashCode() ?? 0
		);
	}
}
